[package]
name = "rusty-roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
bracket-lib = "0.8.7"
legion = "=0.3.1"

[features]
default = ["map_rooms"]
map_rooms = []
map_empty = []
map_cellular_automata = []